name: GitHub Action Demo
on: push
jobs:
  Premier_Job:
    name: Premier-Job
    runs-on: ubuntu-latest
    steps:
      - run: echo "premeier job"
      - run: echo "fin"
  Deuxieme_Job:
    name: Deuxieme-Job
    runs-on: ubuntu-latest
    needs: Premier_Job
    steps:
      - run: echo "deuxieme job"
      - run: echo "fin 2"
